import type { CategoryFilterItem, Restaurant } from "@/src/lib/restaurant-types";

export const categoryFilters: CategoryFilterItem[] = [
  { id: "all", label: "全部" },
  { id: "japanese", label: "日式" },
  { id: "chinese", label: "中式" },
  { id: "snacks", label: "小吃" },
  { id: "coffee", label: "咖啡" },
  { id: "desserts", label: "甜點" },
];

export const mockRestaurants: Restaurant[] = [
  {
    id: "merci-cafe",
    name: "Merci Café",
    imageUrl: "/restaurants/placeholder.svg",
    rating: 4.7,
    reviewCount: 128,
    isOpen: true,
    distanceMeters: 120,
    averagePrice: 230,
    priceMin: 180,
    priceMax: 280,
    tags: ["咖啡", "早午餐", "甜點"],
    category: "coffee",
    isFavorite: true,
  },
  {
    id: "grandma-braised-pork",
    name: "阿嬤滷肉飯",
    imageUrl: "/restaurants/placeholder.svg",
    rating: 4.5,
    reviewCount: 102,
    isOpen: false,
    distanceMeters: 85,
    averagePrice: 65,
    priceMin: 45,
    priceMax: 85,
    tags: ["中式", "小吃"],
    category: "chinese",
    isFavorite: false,
    lastVisited: "2026-06-05",
    notes: "滷汁偏甜，很下飯。",
  },
  {
    id: "yamamoto-ramen",
    name: "山本拉麵",
    imageUrl: "/restaurants/placeholder.svg",
    rating: 4.6,
    reviewCount: 235,
    isOpen: true,
    distanceMeters: 230,
    averagePrice: 200,
    priceMin: 150,
    priceMax: 250,
    tags: ["日式", "拉麵"],
    category: "japanese",
    isFavorite: true,
    lastVisited: "2026-06-10",
    notes: "湯頭濃郁，午間不用排太久。",
  },
];
